<<<<<<< HEAD
title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
=======
theme: jekyll-theme-minimal
>>>>>>> 0460899fe638e11582e8329b1aad2fa4ef84523a
